name: build and test using kxcdev/ocaml-general-gha

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ocaml-general:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test
        uses: kxcdev/ocaml-general-gha@v2
        with:
          build-command: "dune build && dune build @doc"

      - name: ls _build
        run: ls _build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "_build/default/_doc/_html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
