name: build and test using kxcdev/ocaml-general-gha

on: push

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test
        uses: kxcdev/ocaml-general-gha@v2-future
