name: build and test using kxcdev/ocaml-general-gha

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ocaml-general:

    environment:
      name: github-pages
      url: ${{ steps.camlbuild.outputs.odoc-github-pages-url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test
        id: camlbuild
        uses: kxcdev/ocaml-general-gha@v2-future
        with:
          # build-command: "dune build && dune build @doc"
          with-odoc: true
          odoc-deploy-github-pages: true

      - name: ls _build/default
        run: ls _build/default

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     path: ${{ steps.camlbuild.outputs.odoc-site-path }}

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v2
