name: build and test using kxcdev/ocaml-general-gha

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ocaml-general:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.odoc-github-pages-url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test
        id: camlbuild
        uses: kxcdev/ocaml-general-gha@v2-future
        with:
          with-odoc: true
          odoc-upload-artifact: true # could be omitted
          odoc-upload-artifact-name: "github-pages"

          ## waiting for resolution of actions/runner#2009
          # odoc-deploy-github-pages: true

      - name: Setup Pages
        if: ${{ inputs.odoc-deploy-github-pages }}
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
